### ISSUE TITLE
Full example

### ISSUE THREAD

**Issue by yannickl88** [hostnet/webpack-bundle#6]
I'm having some issues getting this all to work. Everything is configured correctly and it is compiling my output to a JS file. However, it is not including the compiled JS.

My twig file:
```html
<html>
    <head>
    <script src="{{ webpack_asset('@AppBundle/app.js').js }}"></script>
    </head>
    <body>
    </body>
</html>
```
My app.js:
```js
document.write("HENK");
```

The output html:
```html
<html>
    <head>
    <script src=""></script>
    </head>
    <body>
    </body>
</html>
```

and the outputed JS: (`app_bundle.app.js`)
```js
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "/";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports) {

	document.write("HENK");

/***/ }
/******/ ]);
```

Am I missing something?

**Comment by haroldiedema** [comment]
What does your webpack configuration look like?

It looks like the tracker can't find your resources.

**Comment by yannickl88** [comment]
My config.yml for webpack
```yaml
webpack:
    bundles:
        - AppBundle
    output:
        path      : "%kernel.root_dir%/../../../web/js/compiled/"
        dump_path : "%kernel.root_dir%/../../../web/bundles"
    node:
        binary:
            linux_x64 : "%kernel.root_dir%/../../../vendor/hostnet/nodejs-lib/bin/node/linux/node-linux"
            darwin    : "%kernel.root_dir%/../../../vendor/hostnet/nodejs-lib/bin/node/mac/node-mac"
        node_modules_path: "%kernel.root_dir%/../../../vendor/hostnet/node-modules-lib/node_modules"
```

**Comment by haroldiedema** [comment]
You're missing the "public_path", which is relative from your web directory (from the browsers' perspective).

You're compiling resources to "/js/compiled", so the public path must be set to "/js/compiled/". Don't forget the trailing slash (I'll fix that later)

**Comment by haroldiedema** [comment]
Check the "ideal configuration" section in the readme. You could pretty much copy-paste that.

**Comment by yannickl88** [comment]
Okay, seems to work now:

config.yml:
```yaml
webpack:
    bundles:
        - AppBundle
    output:
        path        : "%kernel.root_dir%/../../../web/js/compiled/"
        dump_path   : "%kernel.root_dir%/../../../web/bundles"
        public_path : "/js/compiled/"
        common_id   : shared
    loaders:
        css:
            enabled: true
            all_chunks: true
            filename: '[name].css'
        less:
            enabled: true
            all_chunks: true
            filename: '[name].css'
        url:
            enabled: true
        babel:
            enabled: true
    node:
        binary:
            linux_x64 : "%kernel.root_dir%/../../../vendor/hostnet/nodejs-lib/bin/node/linux/node-linux"
            darwin    : "%kernel.root_dir%/../../../vendor/hostnet/nodejs-lib/bin/node/mac/node-mac"
        node_modules_path: "%kernel.root_dir%/../../../vendor/hostnet/node-modules-lib/node_modules"
```
twig file:
```twig
<html>
    <head>
        <script type="text/javascript" src="/js/compiled/shared.js"></script>

        {% webpack css "@AppBundle/app.js" %}
        <link rel="stylesheet" href="{{ asset }}">
        {% endwebpack %}

        {% webpack js "@AppBundle/app.js" %}
        <script src="{{ asset }}"></script>
        {% endwebpack %}
    </head>
    <body>
    Test
    </body>
</html>
```
app.js:
```js
document.write("HENK");
```

**Comment by haroldiedema** [comment]
Looks good.

The nodejs lib creates symlinks of the binaries to your own 'bin' folder, so that config could be shortened.

```yaml
    node:
        binary:
            linux_x64 : "%kernel.root_dir%/../../../bin/node-linux"
            darwin    : "%kernel.root_dir%/../../../bin/node-mac"
```
