### ISSUE TITLE
Output folder is not created

### ISSUE THREAD

**Issue by kristinalyba** [hostnet/webpack-bundle#64]
I am experiencing a problem - the output folder does not get created. 
No errors shown.

`src/App/FrontendBundle/Resources/views/test.html.twig `(copy is in src/App/FrontendBundle/Resources/test.html.twig):
```
<html>
    <head>
    </head>
    <body>
    	<script src="{{ webpack_asset('@FrontendBundle/public/js/test.js').js }}"></script>
    	<script src="{{ webpack_public('@FrontendBundle/js/test.js').js }}"></script>
    </body>
</html>
```
`src/App/FrontendBundle/Resources/assets/js/test.js` (copy is in src/App/FrontendBundle/Resources/assets/public/js and src/App/FrontendBundle/Resources/public/js):
```
alert('test!');
```

config.yml:
```
webpack:
    bundles:
        - FrontendBundle
    output:
        path: '%kernel.root_dir%/../web/compiled/'
        dump_path: '%kernel.root_dir%/../web/bundles/'
        public_path: '/compiled/'
    node:
        binary: '/usr/bin/node'
        node_modules_path: '%kernel.root_dir%/../node_modules'
```

Running as `php bin/console webpack:compile`

Am I missing something? Thanks.
